version: '3.9'

services:
  web:
    build: .
    container_name: apm-web-app
    ports:
      - "8448:8080"
    environment:
      - debug=${debug}
      - secret_key=${secret_key}
      - allowed_hosts=${allowed_hosts}
      - server_host=${server_host}
      - server_port=${server_port}
      - client_host=${client_host}
      - client_port=${client_port}
      - max_retries=${max_retries}
      - api_token=${api_token}
    restart: unless-stopped